config/routes.rb
Attendanceproject::Application.routes.draw do
  devise_for :users

  resources :users
  resources :attendances
  get "home/get"
  
  resources :timetables
  resources :travelfees

   root :to => 'home#get'

end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  # GET /timetables
  # GET /timetables.json
  def index
   #@timetables = Timetable.all
   @timetables = Timetable.paginate(:page=>params[:page],:per_page=>5).find(:all,:conditions=>["jplevel LIKE ? && school LIKE ? " , "%#{params[:jplevel]}%","%#{params[:school]}%"])

      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timetables }
    end
  end

  # GET /timetables/1
  # GET /timetables/1.json
  def show
    @timetable = Timetable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timetable }
    end
  end

  # GET /timetables/new
  # GET /timetables/new.json
  def new
    @timetable=Timetable.all
    @timetable = Timetable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timetable }
    end
  end

  # GET /timetables/1/edit
  def edit
    @timetable = Timetable.find(params[:id])
  end

  # POST /timetables
  # POST /timetables.json
  def create 
     @timetable = Timetable.new(params[:timetable])

    respond_to do |format|
      if @timetable.save
        format.html { redirect_to @timetable, notice: 'Timetable was successfully created.' }
        format.json { render json: @timetable, status: :created, location: @timetable }
      else
        format.html { render action: "new" }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /timetables/1
  # PUT /timetables/1.json
  def update
    @timetable = Timetable.find(params[:id])

    respond_to do |format|
      if @timetable.update_attributes(params[:timetable])
        format.html { redirect_to @timetable, notice: 'Timetable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timetables/1
  # DELETE /timetables/1.json
  def destroy
    @timetable = Timetable.find(params[:id])
    @timetable.destroy

    respond_to do |format|
      format.html { redirect_to timetables_url }
      format.json { head :no_content }
    end
  end
end

app/views/timetables/_form.html.erb
<%= form_for(@timetable) do |f| %>
  <% if @timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>

      <ul>
      <% @timetable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :jplevel %><br />
   <%= f.select :jplevel, options_for_select(%w[1 2 3 4 5])%>
  </div>
  <div class="field">
    <%= f.label :classname %><br />
    <%= f.text_field :classname %>
  </div>
  <div class="field">
    <%= f.label :school %><br />
     <%= f.select :school, options_for_select(%w[Win Momiji GIC])%>
  </div>
  <div class="field">
    <%= f.label :starttime %><br />
    <%= f.time_select :starttime %>
  </div>
  <div class="field">
    <%= f.label :endtime %><br />
    <%= f.time_select :endtime %>
  </div>
  <div class="field">
    <%= f.label :sunday %><br />
    <%= f.check_box :sunday %>
  </div>
  <div class="field">
    <%= f.label :monday %><br />
    <%= f.check_box :monday %>
  </div>
  <div class="field">
    <%= f.label :tuesday %><br />
    <%= f.check_box :tuesday %>
  </div>
  <div class="field">
    <%= f.label :wednesday %><br />
    <%= f.check_box :wednesday %>
  </div>
  <div class="field">
    <%= f.label :thursday %><br />
    <%= f.check_box :thursday %>
  </div>
  <div class="field">
    <%= f.label :friday %><br />
    <%= f.check_box :friday %>
  </div>
  <div class="field">
    <%= f.label :saturaday %><br />
    <%= f.check_box :saturaday %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select :startdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timetables/edit.html.erb
<h1>Editing timetable</h1>

<%= render 'form' %>

<%= link_to 'Show', @timetable %> |
<%= link_to 'Back', timetables_path %>

app/views/timetables/index.html.erb
<h1>Listing timetables</h1>
<%= form_tag timetables_path, :method => "get" do%>
<table>
 <tr>
  <td>jplevel</td>
  <td><%= select_tag "jplevel", options_for_select(%w[1 2 3 4 5]) %></td>
 </tr>
 <tr>
  <td>Month</td>
  <td><%= select_tag "month", options_for_select(%w[Win Momiji GIC])%></td>
 </tr>
 </table>
<%= submit_tag :find %>
<% end %>
<table>
  <tr>
    <th>Jplevel</th>
    <th>Classname</th>
    <th>School</th>
    <th>Starttime</th>
    <th>Endtime</th>
    <th>Sunday</th>
    <th>Monday</th>
    <th>Tuesday</th>
    <th>Wednesday</th>
    <th>Thursday</th>
    <th>Friday</th>
    <th>Saturaday</th>
    <th>Duration</th>
    <th>Startdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @timetables.each do |timetable| %>
  <tr>
    <td><%= timetable.jplevel %></td>
    <td><%= timetable.classname %></td>
    <td><%= timetable.school %></td>
    <td><%= timetable.starttime %></td>
    <td><%= timetable.endtime %></td>
    <td><%= timetable.sunday %></td>
    <td><%= timetable.monday %></td>
    <td><%= timetable.tuesday %></td>
    <td><%= timetable.wednesday %></td>
    <td><%= timetable.thursday %></td>
    <td><%= timetable.friday %></td>
    <td><%= timetable.saturaday %></td>
    <td><%= timetable.duration %></td>
    <td><%= timetable.startdate %></td>
    <td><%= link_to 'Show', timetable %></td>
    <td><%= link_to 'Edit', edit_timetable_path(timetable) %></td>
    <td><%= link_to 'Destroy', timetable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @users %>

<%= link_to 'New Timetable', new_timetable_path %>

app/views/timetables/new.html.erb
<h1>New timetable</h1>

<%= render 'form' %>

<%= link_to 'Back', timetables_path %>

app/views/timetables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Jplevel:</b>
  <%= @timetable.jplevel %>
</p>

<p>
  <b>Classname:</b>
  <%= @timetable.classname %>
</p>

<p>
  <b>School:</b>
  <%= @timetable.school %>
</p>

<p>
  <b>Starttime:</b>
  <%= @timetable.starttime %>
</p>

<p>
  <b>Endtime:</b>
  <%= @timetable.endtime %>
</p>

<p>
  <b>Sunday:</b>
  <%= @timetable.sunday %>
</p>

<p>
  <b>Monday:</b>
  <%= @timetable.monday %>
</p>

<p>
  <b>Tuesday:</b>
  <%= @timetable.tuesday %>
</p>

<p>
  <b>Wednesday:</b>
  <%= @timetable.wednesday %>
</p>

<p>
  <b>Thursday:</b>
  <%= @timetable.thursday %>
</p>

<p>
  <b>Friday:</b>
  <%= @timetable.friday %>
</p>

<p>
  <b>Saturaday:</b>
  <%= @timetable.saturaday %>
</p>

<p>
  <b>Duration:</b>
  <%= @timetable.duration %>
</p>

<p>
  <b>Startdate:</b>
  <%= @timetable.startdate %>
</p>


<%= link_to 'Edit', edit_timetable_path(@timetable) %> |
<%= link_to 'Back', timetables_path %>