config/routes.rb
Attendanceproject::Application.routes.draw do
  devise_for :users

  resources :users
  resources :attendances
  get "home/get"
  
  resources :timetables
  resources :travelfees

   root :to => 'home#get'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def get
  	@attendances=Attendance.all
  end
end
  	
    

    

app/views/home/get.html.erb
<br>
<br>


<table>
  <tr>
    <th>Userid</th>
    <th>Date</th>
    <th>Reachtime</th>
    <th>Leavetime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @attendances.each do |attendance| %>
  <tr>
    <td><%= attendance.userid %></td>
    <td><%= attendance.date %></td>
    <td><%= attendance.reachtime %></td>
    <td><%= attendance.leavetime %></td>
    <td><%= link_to 'Show', attendance %></td>
    <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
    <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>


</table>

<br />

<%= link_to 'See More', attendances_path %>

app/views/home/index.html.erb
<h1>Listing attendances</h1>

<table>
  <tr>
    <th>Userid</th>
    <th>Date</th>
    <th>Reachtime</th>
    <th>Leavetime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendances.each do |attendance| %>
  <tr>
    <td><%= attendance.userid %></td>
    <td><%= attendance.date %></td>
    <td><%= attendance.reachtime %></td>
    <td><%= attendance.leavetime %></td>
    <td><%= link_to 'Show', attendance %></td>
    <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
    <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendance', new_attendance_path %>

app/views/home/timetable.html.erb
<h1>Time Table</h1>
<p>This is time table</p>

app/views/home/travelfee.html.erb
<h1>Travel Fee</h1>
<p>Calcualte travel fee</p>

app/views/home/user.html.erb
<h1>User</h1>
</p>Fill this form</p>