config/routes.rb
Attendanceproject::Application.routes.draw do
  devise_for :users

  resources :users
  resources :attendances
  get "home/get"
  
  resources :timetables
  resources :travelfees

   root :to => 'home#get'

end

app/models/travelfee.rb
class Travelfee < AciveRecord::Base
  attr_accessible :classname, :date, :travel_fee, :userid
  belongs_to :user
  #belongs_to :timetable
  validates :userid,numericality:{only_integer:true}, presence:true
  validates :travel_fee,numericality:{only_integer:true}, presence:true 
  validates :classname, presence: true
  self.per_page=5
end
WillPaginate.per_page=5

app/controllers/travelfees_controller.rb
require "users_controller"
require "timetables_controller"
class TravelfeesController < ApplicationController
  

  # GET /travelfees
  # GET /travelfees.json
  def index
    @users = User.all   
    @travelfees = Travelfee.paginate(:page=>params[:page],:per_page=>5).find(:all,:conditions=>["userid LIKE ? " , "%#{params[:userid]}%"])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @travelfees , json: @users }

    end
  end

  # GET /travelfees/1
  # GET /travelfees/1.json
  def show
    @travelfee = Travelfee.find(params[:id])
    @users = User.all
    @travelfee = Travelfee.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @travelfee }
    end
  end

  # GET /travelfees/new
  # GET /travelfees/new.json
  def new
    @users = User.all
    @timetables = Timetable.all
    @travelfee = Travelfee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @travelfee }
    end
  end

  # GET /travelfees/1/edit
  def edit
    @travelfee = Travelfee.find(params[:id])
  end

  # POST /travelfees
  # POST /travelfees.json
  def create
    @users= User.all
    @timetables = Timetable.all
    @travelfee = Travelfee.new(params[:travelfee])
    
    respond_to do |format|
      if @travelfee.save
        format.html { redirect_to @travelfee, notice: 'Travelfee was successfully created.' }
        format.json { render json: @travelfee, status: :created, location: @travelfee }
      else
        format.html { render action: "new" }
        format.json { render json: @travelfee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /travelfees/1
  # PUT /travelfees/1.json
  def update
    @travelfee = Travelfee.find(params[:id])
   @users= User.all
    respond_to do |format|
      if @travelfee.update_attributes(params[:travelfee])
        format.html { redirect_to @travelfee, notice: 'Travelfee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @travelfee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travelfees/1
  # DELETE /travelfees/1.json
  def destroy
    @travelfee = Travelfee.find(params[:id])
    @travelfee.destroy

    respond_to do |format|
      format.html { redirect_to travelfees_url }
      format.json { head :no_content }
    end
  end
end

app/views/travelfees/_form.html.erb
<%= simple_form_for(@travelfee) do |f| %>
  <% if @travelfee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@travelfee.errors.count, "error") %> prohibited this travelfee from being saved:</h2>

      <ul>
      <% @travelfee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.input :userid, :as => :select, :collection => @users.map{ |u| [u.userid,u.userid]} %>
  </div>
  <div class="field">
    <%= f.input :classname, :as => :select, :collection => @timetables.map { |u| [u.classname,u.classname]} %> 
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :travelfee %><br />
    <%= f.number_field :travelfee %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/travelfees/index.html.erb
<html>
<h1>Listing travelfees</h1>

<%=form_tag travelfees_path, :method => "get" do %>
<table>
 <tr>
  <td>userid </td>
  <td><%= select_tag :userid, options_for_select(@users.collect{|u| [u.userid,u.userid]}) %></td>
 </tr>
 <tr>
  <td>From Date</td>
  <td><%= date_select :date,params[:date] %></td>
 </tr>
  <td>End Date</td>
  <td><%= date_select :date,params[:date] %></td>
 </tr>
</table>
<%= submit_tag :find %>
<% end %>


<table>
  <tr>
    <th>Userid</th>
    <th>Classname</th>
    <th>Date</th>
    <th>Travel fee</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @travelfees.each do |travelfee| %>
  <tr>
    <td><%= travelfee.userid %></td>
    <td><%= travelfee.classname %></td>
    <td><%= travelfee.date %></td>
    <td><%= travelfee.travelfee %></td>
    <td><%= link_to 'Show', travelfee %></td>
    <td><%= link_to 'Edit', edit_travelfee_path(travelfee) %></td>
    <td><%= link_to 'Destroy', travelfee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>


</table>

<br />

<%= will_paginate @travelfees %>
<%= link_to 'New Travel Fee', new_travelfee_path %>
</html>